package jmultigwas;

import java.awt.Component;
import java.io.File;
import java.util.prefs.Preferences;
import javax.swing.JFileChooser;

public class ViewInputs extends javax.swing.JPanel {

    // Attributes
    Model model;
    Controller controller;
    String outputDir;
    Preferences prefs;

    final JFileChooser fc = new JFileChooser();
    String LAST_USED_FOLDER = "";

    // Methods
    public ViewInputs(Controller controller, Model model) {
        this.controller = controller;
        this.model = model;
        initComponents();
        fieldOutputDir.setText(getLastDir().toString());
        setDefaults();
    }

    public File getLastDir() {
        prefs = Preferences.userRoot().node(getClass().getName());
        File curFile = new File(prefs.get(LAST_USED_FOLDER, new File(".").getAbsolutePath()));
        return curFile;
    }

    public void setDefaults() {
        fieldOutputDir.setText(System.getProperty("user.home"));
        fieldSignificance.setText("0.05");
        fieldCorrection.setSelectedIndex(0);
        fieldModel.setSelectedIndex(0);
        fieldSNPs.setSelectedIndex(4);
        fieldFiltering.setSelectedIndex(0);
        fieldFilterMAF.setText("0.01");
        fieldFilterMIND.setText("0.1");
        fieldFilterGENO.setText("0.1");
        fieldFilterHWE.setText("1e-10");
    }

    public void clearInputs() {
        fieldOutputDir.setText("");
        fieldGeno.setText("");
        fieldPheno.setText("");
        fieldSignificance.setText("");
        fieldCorrection.setSelectedIndex(0);
        fieldModel.setSelectedIndex(0);
        fieldSNPs.setSelectedIndex(4);
        fieldFiltering.setSelectedIndex(0);
        fieldFilterMAF.setText("");
        fieldFilterMIND.setText("");
        fieldFilterGENO.setText("");
        fieldFilterHWE.setText("");
        setEnabledInputs (false);
    }

    public void setEnabledInputs(Boolean flag) {
        Component components[] = this.getComponents();

        for (Component c : panelPaths.getComponents()) 
            c.setEnabled(flag);
       
        for (Component c : panelParameters.getComponents()) 
            c.setEnabled(flag);
        
        for (Component c : panelFilters.getComponents()) 
            c.setEnabled(flag);

        fieldOutputDir.setEnabled(true);
        labelOutputDir.setEnabled(true);
        selOutputDir.setEnabled(true);
    }

    public String readInputData() {
        StringBuffer txt = new StringBuffer(500);
        String ln = System.lineSeparator();
        txt.append("default:" + ln);
        txt.append("  genotypeFile         : " + '"' + fieldGeno.getText() + '"' + ln);
        txt.append("  phenotypeFile        : " + '"' + fieldPheno.getText() + '"' + ln);
        txt.append("  significanceLevel    : " + fieldSignificance.getText() + ln);
        txt.append("  correctionMethod     : " + '"' + fieldCorrection.getSelectedItem().toString() + '"' + ln);
        txt.append("  gwasModel            : " + fieldModel.getSelectedItem().toString() + ln);
        txt.append("  nBest                : " + fieldSNPs.getSelectedItem().toString() + ln);
        txt.append("  filtering            : " + fieldFiltering.getSelectedItem().toString() + ln);
        txt.append("  MAF                  : " + fieldFilterMAF.getText() + ln);
        txt.append("  MIND                 : " + fieldFilterMIND.getText() + ln);
        txt.append("  GENO                 : " + fieldFilterGENO.getText() + ln);
        txt.append("  HWE                  : " + fieldFilterHWE.getText() + ln);

        return txt.toString();
    }

    public void runApplication() {
        String outputDir = fieldOutputDir.getText();
        String fieldsText = readInputData();

        controller.onRunApplication();

        model.runApplication(outputDir, fieldsText.toString());
    }

    public String getOutputDir() {
        outputDir = fieldOutputDir.getText();
        return outputDir;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        buttonRun = new javax.swing.JButton();
        buttonOpen = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        panelInputs = new javax.swing.JPanel();
        panelPaths = new javax.swing.JPanel();
        labelOutputDir = new javax.swing.JLabel();
        fieldOutputDir = new javax.swing.JTextField();
        fieldPheno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldGeno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        selOutputDir = new javax.swing.JButton();
        selGenotypeBt = new javax.swing.JButton();
        selPhenotypeBt = new javax.swing.JButton();
        panelParameters = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fieldModel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        fieldSignificance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldCorrection = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        fieldSNPs = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fieldFiltering = new javax.swing.JComboBox<>();
        panelFilters = new javax.swing.JPanel();
        fieldFilterMIND = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldFilterGENO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldFilterHWE = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldFilterMAF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new java.awt.BorderLayout());

        panelTitle.setBackground(java.awt.Color.blue);
        panelTitle.setForeground(java.awt.Color.yellow);

        jLabel13.setForeground(java.awt.Color.yellow);
        jLabel13.setText("Input Parameters");
        panelTitle.add(jLabel13);

        add(panelTitle, java.awt.BorderLayout.PAGE_START);

        panelButtons.setBackground(new java.awt.Color(153, 153, 255));

        buttonRun.setText("Run");
        buttonRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRunActionPerformed(evt);
            }
        });
        panelButtons.add(buttonRun);

        buttonOpen.setText("Open...");
        panelButtons.add(buttonOpen);

        buttonSave.setText("Save...");
        panelButtons.add(buttonSave);

        add(panelButtons, java.awt.BorderLayout.SOUTH);

        panelInputs.setBackground(new java.awt.Color(204, 204, 255));

        panelPaths.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelOutputDir.setText("Output Folder:");

        fieldOutputDir.setText("/home/lg/AAA");
        fieldOutputDir.setToolTipText("Select genotype file");

        fieldPheno.setText("/home/lg/agrosavia/development/multiGWAS/examples/example-phenotype.tbl");
        fieldPheno.setToolTipText("Select phenotype file");
        fieldPheno.setPreferredSize(new java.awt.Dimension(90, 19));

        jLabel2.setText("Input Phenotype:");

        fieldGeno.setText("/home/lg/agrosavia/development/multiGWAS/examples/example-genotype.tbl");
        fieldGeno.setToolTipText("Select genotype file");
        fieldGeno.setPreferredSize(new java.awt.Dimension(90, 19));

        jLabel12.setText("Input Genotype:");

        selOutputDir.setText("Select...");
        selOutputDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selOutputDirActionPerformed(evt);
            }
        });

        selGenotypeBt.setText("Select...");
        selGenotypeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selGenotypeBtActionPerformed(evt);
            }
        });

        selPhenotypeBt.setText("Select...");
        selPhenotypeBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPhenotypeBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPathsLayout = new javax.swing.GroupLayout(panelPaths);
        panelPaths.setLayout(panelPathsLayout);
        panelPathsLayout.setHorizontalGroup(
            panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPathsLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(labelOutputDir)
                        .addComponent(jLabel12))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fieldGeno, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                        .addComponent(fieldOutputDir)
                        .addComponent(fieldPheno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selGenotypeBt)
                            .addComponent(selPhenotypeBt, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(selOutputDir, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap()))
        );
        panelPathsLayout.setVerticalGroup(
            panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPathsLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelOutputDir)
                        .addComponent(fieldOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selOutputDir, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                    .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldPheno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPathsLayout.createSequentialGroup()
                            .addGroup(panelPathsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(fieldGeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(selGenotypeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(selPhenotypeBt, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(15, 15, 15)))
        );

        panelParameters.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("GWAS Model:");

        fieldModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full", "Naive" }));

        jLabel3.setText("Significance Level:");

        fieldSignificance.setText("0.05");

        jLabel4.setText("Correction Method:");

        fieldCorrection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bonferroni", "FDR" }));

        jLabel5.setText("Number of Best SNPs:");

        fieldSNPs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        fieldSNPs.setSelectedIndex(7);

        jLabel6.setText("Filtering:");

        fieldFiltering.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRUE", "FALSE" }));
        fieldFiltering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFilteringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParametersLayout = new javax.swing.GroupLayout(panelParameters);
        panelParameters.setLayout(panelParametersLayout);
        panelParametersLayout.setHorizontalGroup(
            panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParametersLayout.createSequentialGroup()
                        .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldSignificance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelParametersLayout.createSequentialGroup()
                        .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParametersLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParametersLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(95, 95, 95))
                            .addGroup(panelParametersLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(22, 22, 22)))
                        .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldFiltering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldSNPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldCorrection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelParametersLayout.setVerticalGroup(
            panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParametersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldSignificance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldCorrection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldSNPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelParametersLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(fieldFiltering, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFilters.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldFilterMIND.setText("0.1");

        jLabel9.setText("MIND;");

        fieldFilterGENO.setText("0.1");

        jLabel10.setText("GENO:");

        fieldFilterHWE.setText("1e-10");

        jLabel11.setText("HWE:");

        fieldFilterMAF.setText("0.01");

        jLabel7.setText("MAF:");

        javax.swing.GroupLayout panelFiltersLayout = new javax.swing.GroupLayout(panelFilters);
        panelFilters.setLayout(panelFiltersLayout);
        panelFiltersLayout.setHorizontalGroup(
            panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldFilterMIND, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldFilterGENO, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fieldFilterHWE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fieldFilterMAF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        panelFiltersLayout.setVerticalGroup(
            panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFiltersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldFilterMAF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldFilterMIND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldFilterGENO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldFilterHWE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInputsLayout = new javax.swing.GroupLayout(panelInputs);
        panelInputs.setLayout(panelInputsLayout);
        panelInputsLayout.setHorizontalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPaths, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelInputsLayout.setVerticalGroup(
            panelInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(panelFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        add(panelInputs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void selOutputDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selOutputDirActionPerformed
        if (evt.getSource() == selOutputDir) {
            fc.setCurrentDirectory(getLastDir());
            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            int returnVal = fc.showOpenDialog(ViewInputs.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                prefs.put(LAST_USED_FOLDER, fc.getSelectedFile().getParent());
                //This is where a real application would open the file.
                fieldOutputDir.setText(file.getAbsolutePath());
                setEnabledInputs(true);
            }
        }
    }//GEN-LAST:event_selOutputDirActionPerformed

    private void buttonRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRunActionPerformed
        runApplication();
    }//GEN-LAST:event_buttonRunActionPerformed

    private void selPhenotypeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPhenotypeBtActionPerformed
        if (evt.getSource() == selPhenotypeBt) {
            fc.setCurrentDirectory(getLastDir());
            int returnVal = fc.showOpenDialog(ViewInputs.this);
            fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                //This is where a real application would open the file.
                fieldPheno.setText(file.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_selPhenotypeBtActionPerformed

    private void selGenotypeBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selGenotypeBtActionPerformed
        //Handle open button action.
        if (evt.getSource() == selGenotypeBt) {
            fc.setCurrentDirectory(getLastDir());
            fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            int returnVal = fc.showOpenDialog(ViewInputs.this);

            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                //This is where a real application would open the file.
                fieldGeno.setText(file.getAbsolutePath());
                prefs.put(LAST_USED_FOLDER, fc.getSelectedFile().getParent());
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_selGenotypeBtActionPerformed

    private void fieldFilteringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFilteringActionPerformed
        boolean flag = false;
        System.out.println (fieldFiltering.getSelectedItem().toString());
        if (fieldFiltering.getSelectedItem().toString().equals ("FALSE")) 
            flag = false;
         else 
            flag = true;
        
        for (Component c : panelFilters.getComponents()) 
            c.setEnabled(flag);      
    }//GEN-LAST:event_fieldFilteringActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonRun;
    private javax.swing.JButton buttonSave;
    private javax.swing.JComboBox<String> fieldCorrection;
    private javax.swing.JTextField fieldFilterGENO;
    private javax.swing.JTextField fieldFilterHWE;
    private javax.swing.JTextField fieldFilterMAF;
    private javax.swing.JTextField fieldFilterMIND;
    private javax.swing.JComboBox<String> fieldFiltering;
    private javax.swing.JTextField fieldGeno;
    private javax.swing.JComboBox<String> fieldModel;
    private javax.swing.JTextField fieldOutputDir;
    private javax.swing.JTextField fieldPheno;
    private javax.swing.JComboBox<String> fieldSNPs;
    private javax.swing.JTextField fieldSignificance;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelOutputDir;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JPanel panelFilters;
    private javax.swing.JPanel panelInputs;
    private javax.swing.JPanel panelParameters;
    private javax.swing.JPanel panelPaths;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JButton selGenotypeBt;
    private javax.swing.JButton selOutputDir;
    private javax.swing.JButton selPhenotypeBt;
    // End of variables declaration//GEN-END:variables
}
